import type { FastifyInstance,FastifyReply,FastifyRequest } from 'fastify'
import {z} from 'zod'
import {bearerToken,type AuthService,type AuthenticatedUser} from '../auth/auth-service.js'
import type {CollaborationService} from './service.js'
const uuid=z.string().uuid(),session=z.object({sessionId:uuid})
export async function registerCollaborationRoutes(app:FastifyInstance,o:{authService:AuthService;collaborationService:CollaborationService}){
 const auth=async(r:FastifyRequest,p:FastifyReply):Promise<AuthenticatedUser|null>=>{try{return await o.authService.verifyAccessToken(bearerToken(r.headers.authorization))}catch{await p.code(401).send({error:{code:'UNAUTHORIZED',message:'Authentication required'}});return null}}
 app.post('/v1/sessions/:sessionId/invites',async(r,p)=>{const u=await auth(r,p);if(!u)return;const {sessionId}=session.parse(r.params),{inviteeId}=z.object({inviteeId:uuid}).parse(r.body);return p.code(201).send({invite:await o.collaborationService.invite(sessionId,u.id,inviteeId)})})
 app.get('/v1/invites',async(r,p)=>{const u=await auth(r,p);if(u)return p.send({invites:await o.collaborationService.pendingInvites(u.id)})})
 app.post('/v1/invites/:inviteId/:action',async(r,p)=>{const u=await auth(r,p);if(!u)return;const x=z.object({inviteId:uuid,action:z.enum(['accept','decline'])}).parse(r.params);return p.send(x.action==='accept'?await o.collaborationService.acceptInvite(x.inviteId,u.id):{invite:await o.collaborationService.declineInvite(x.inviteId,u.id)})})
 app.get('/v1/sessions/:sessionId/chat',async(r,p)=>{const u=await auth(r,p);if(!u)return;const {sessionId}=session.parse(r.params);return p.send({messages:await o.collaborationService.listChat(sessionId,u.id)})})
 app.post('/v1/sessions/:sessionId/chat',async(r,p)=>{const u=await auth(r,p);if(!u)return;const {sessionId}=session.parse(r.params),{content}=z.object({content:z.string()}).parse(r.body);return p.code(201).send({message:await o.collaborationService.sendChat(sessionId,u.id,content)})})
 app.get('/v1/sessions/:sessionId/explain',async(r,p)=>{const u=await auth(r,p);if(!u)return;const {sessionId}=session.parse(r.params);return p.send({state:await o.collaborationService.getExplainState(sessionId,u.id),messages:await o.collaborationService.listExplainMessages(sessionId,u.id),annotations:await o.collaborationService.listAnnotations(sessionId,u.id)})})
 app.post('/v1/sessions/:sessionId/explain/activate',async(r,p)=>{const u=await auth(r,p);if(!u)return;const {sessionId}=session.parse(r.params),{targetSlot}=z.object({targetSlot:z.enum(['A','B'])}).parse(r.body);return p.send(await o.collaborationService.activateExplain(sessionId,u.id,targetSlot))})
 app.post('/v1/sessions/:sessionId/explain/deactivate',async(r,p)=>{const u=await auth(r,p);if(!u)return;const {sessionId}=session.parse(r.params);return p.send({state:await o.collaborationService.deactivateExplain(sessionId,u.id)})})
 app.post('/v1/sessions/:sessionId/explain/messages',async(r,p)=>{const u=await auth(r,p);if(!u)return;const {sessionId}=session.parse(r.params),{content}=z.object({content:z.string()}).parse(r.body);return p.code(201).send({message:await o.collaborationService.sendExplainMessage(sessionId,u.id,content)})})
 app.post('/v1/sessions/:sessionId/explain/annotations',async(r,p)=>{const u=await auth(r,p);if(!u)return;const {sessionId}=session.parse(r.params),body=z.object({targetSlot:z.enum(['A','B']),startLine:z.number().int().positive().nullable().default(null),endLine:z.number().int().positive().nullable().default(null),type:z.enum(['highlight','pointer','note']),text:z.string().nullable().default(null)}).parse(r.body);return p.code(201).send({annotation:await o.collaborationService.addAnnotation(sessionId,u.id,body)})})
 app.delete('/v1/sessions/:sessionId/explain/annotations/:annotationId',async(r,p)=>{const u=await auth(r,p);if(!u)return;const {sessionId,annotationId}=z.object({sessionId:uuid,annotationId:uuid}).parse(r.params);await o.collaborationService.removeAnnotation(sessionId,annotationId,u.id);return p.code(204).send()})
}
